version: "3.8"

services:
  link-shortener-backend:
    build: ./backend
    container_name: link-shortener-backend
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - link-shortener-network
    depends_on:
      - link-shortener-db
    environment:
      API_PORT: ${API_PORT}
      NGINX_PORT: ${NGINX_PORT}
      HOST: ${HOST}
    env_file:
      - .env

  link-shortener-db:
    image: postgres
    container_name: link-shortener-db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - linkShortenerDB:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - link-shortener-network
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx-proxy
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - link-shortener-backend
    networks:
      - link-shortener-network

  link-shortener-backend-tests:
    build: ./backend
    container_name: link-shortener-test
    command: npm run test:e2e
    environment:
      API_PORT: ${API_PORT}
      NGINX_PORT: ${NGINX_PORT}
      HOST: ${HOST}
    env_file:
      - .env
    depends_on:
      - link-shortener-db
    networks:
      - link-shortener-network

volumes:
  linkShortenerDB:

networks:
  link-shortener-network:
